#!/usr/bin/env python3
"""Assert the seam between `src/web/` and the Figma Make export it is ported from.

`src/web/` is the application; `figma/` is the export, applied by hand. The failure this
guards against is silent: a re-export that replaces the API wiring with mock data still
builds, still runs, and still looks right. `src/web/UPSTREAM.md` is the procedure.

Run from the repository root:

    python3 scripts/web-seam.py           # the checks
    python3 scripts/web-seam.py --plan    # the port worklist for the export on HEAD
"""

import re
import subprocess
import sys
from difflib import SequenceMatcher
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "figma"
WEB = ROOT / "src" / "web"
RECORD = WEB / "UPSTREAM.md"
BASELINE = re.compile(r"^Baseline: ([0-9a-f]{7,40})\s*$", re.M)
BEGIN = "@integration:begin"
END = "@integration:end"
SKIP_DIRS = {".git", "node_modules", "dist", ".vite"}

# Upstream files the seam check cannot read a marker in, each with the reason it cannot.
#
# `package.json` is JSON, which has no comment, and pnpm rewrites it whole on the next
# `pnpm add`; `pnpm-lock.yaml` is generated by pnpm and its every line moves when a
# dependency does. A marker in either would be illegal or would not survive one command, so
# the exemption is recorded here rather than pretended at with a marker that is not there.
UNMARKABLE = {
    "package.json": "JSON has no comment, and pnpm rewrites the file whole on `pnpm add`",
    "pnpm-lock.yaml": "generated by pnpm, and rewritten on every dependency change",
}


def relative(path):
    return str(path.relative_to(ROOT))


def git(*args):
    """Run git from the repository root and return its stdout, or None if it failed."""
    done = subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, check=False
    )
    return done.stdout if done.returncode == 0 else None


def upstream_files():
    """Every file under `figma/`, as paths relative to it."""
    return [
        path.relative_to(UPSTREAM)
        for path in sorted(UPSTREAM.rglob("*"))
        if path.is_file()
        and not any(part in SKIP_DIRS for part in path.relative_to(UPSTREAM).parts)
        and path.name != ".DS_Store"
    ]


def lines_of(path):
    """A file's lines, or None when it is not text this script can compare."""
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError:
        return None


def marked_ranges(lines):
    """The 1-indexed inclusive line ranges the seam markers enclose."""
    ranges, opened = [], None
    for number, line in enumerate(lines, start=1):
        if BEGIN in line and opened is None:
            opened = number
        elif END in line and opened is not None:
            ranges.append((opened, number))
            opened = None
    return ranges


def covers(ranges, start, end):
    """Whether a 1-indexed range, or the point before an empty one, lies inside `ranges`.

    The empty case is a pure deletion, which has no lines of its own left to point at: the
    junction `start - 1` is what has to fall inside the seam. Without it, removing a line
    the integration still supplies would be reported as drift against itself.
    """
    if start > end:
        return any(first <= start - 1 <= last for first, last in ranges)
    return any(start <= last and first <= end for first, last in ranges)


def recorded_baseline():
    """The baseline commit named in the record, or None."""
    if not RECORD.exists():
        return None
    found = BASELINE.search(RECORD.read_text(encoding="utf-8"))
    return found.group(1) if found else None


def drift_is_confined_to_the_seam():
    """Every difference from upstream falls in a marked region of the integrated file."""
    failures = []
    for path in upstream_files():
        if str(path) in UNMARKABLE:
            continue
        integrated_path = WEB / path
        upstream = lines_of(UPSTREAM / path)
        integrated = lines_of(integrated_path) if integrated_path.exists() else None
        if upstream is None or integrated is None:
            continue
        seam = marked_ranges(integrated)
        matcher = SequenceMatcher(None, upstream, integrated, autojunk=False)
        for tag, i1, i2, j1, j2 in matcher.get_opcodes():
            if tag == "equal" or covers(seam, j1 + 1, j2):
                continue
            failures.append(
                f"{relative(integrated_path)}:{j1 + 1}: differs from "
                f"{relative(UPSTREAM / path)} outside the seam"
            )
    return failures


def every_upstream_file_is_still_here():
    """A re-export may replace what it ships; it may not take away what it does not."""
    return [
        f"{relative(UPSTREAM / path)} has no counterpart at {relative(WEB / path)}"
        for path in upstream_files()
        if not (WEB / path).exists()
    ]


def markers_are_balanced():
    """No begin without a later end, and no end without one."""
    failures = []
    for path in upstream_files():
        integrated = WEB / path
        lines = lines_of(integrated) if integrated.exists() else None
        if lines is None:
            continue
        opened = None
        for number, line in enumerate(lines, start=1):
            if BEGIN in line:
                if opened is not None:
                    failures.append(
                        f"{relative(integrated)}:{number}: a seam begins inside the "
                        f"seam opened at line {opened}"
                    )
                opened = number
            elif END in line:
                if opened is None:
                    failures.append(
                        f"{relative(integrated)}:{number}: a seam ends without beginning"
                    )
                opened = None
        if opened is not None:
            failures.append(
                f"{relative(integrated)}:{opened}: the seam is never closed"
            )
    return failures


def the_baseline_is_recorded_and_real():
    """The record names a real commit, holding the export, that this branch descends from."""
    baseline = recorded_baseline()
    if baseline is None:
        return [f"{relative(RECORD)}: no readable `Baseline: <commit>` line"]
    if git("cat-file", "-e", f"{baseline}^{{commit}}") is None:
        return [f"{relative(RECORD)}: baseline {baseline} is not a commit in this repository"]
    if git("cat-file", "-e", f"{baseline}:figma") is None:
        return [f"{relative(RECORD)}: baseline {baseline} carries no figma/ tree"]
    if subprocess.run(
        ["git", "merge-base", "--is-ancestor", baseline, "HEAD"],
        cwd=ROOT,
        capture_output=True,
        check=False,
    ).returncode != 0:
        return [f"{relative(RECORD)}: baseline {baseline} is not an ancestor of HEAD"]
    return []


# The upstream files the integration's wiring lives in. A copy of the export over one of these
# takes the markers away with the wiring, and the result — no markers, no differences — is
# indistinguishable from a file that was never wired at all. Drift cannot catch that, because
# a clobbered file has no drift; this is the check that can.
WIRED = ["src/App.tsx"]


def the_wired_files_still_carry_a_seam():
    """Every file the wiring lives in still has a marked region in it."""
    failures = []
    for name in WIRED:
        integrated = WEB / name
        lines = lines_of(integrated) if integrated.exists() else None
        if lines is None or not marked_ranges(lines):
            failures.append(
                f"{relative(integrated)}: carries no seam, so it is either unwired or a copy "
                f"of {relative(UPSTREAM / name)} has been taken over it"
            )
    return failures


def the_exemptions_name_real_files():
    """An exemption for a file upstream does not ship exempts nothing and hides a mistake."""
    shipped = {str(path) for path in upstream_files()}
    return [
        f"{path} is exempt from the seam check but is not a file the export ships"
        for path in UNMARKABLE
        if path not in shipped
    ]


CHECKS = [
    ("The baseline is a commit that holds the export", the_baseline_is_recorded_and_real),
    ("Every file the export ships is still here", every_upstream_file_is_still_here),
    ("The seam markers are balanced", markers_are_balanced),
    ("Drift from the export stays inside the seam", drift_is_confined_to_the_seam),
    ("The wired files still carry a seam", the_wired_files_still_carry_a_seam),
    ("Every exemption names a file the export ships", the_exemptions_name_real_files),
]


def plan():
    """Print what upstream changed since the baseline, and how to port each file."""
    baseline = recorded_baseline()
    if baseline is None:
        print(f"{relative(RECORD)}: no readable `Baseline: <commit>` line")
        return 1

    at_baseline = git("ls-tree", "-r", "--name-only", f"{baseline}:figma")
    at_head = git("ls-tree", "-r", "--name-only", "HEAD:figma")
    if at_baseline is None or at_head is None:
        print("the export is not committed at both the baseline and HEAD")
        return 1
    before, after = set(at_baseline.split()), set(at_head.split())

    print(f"porting {relative(UPSTREAM)} from {baseline} to HEAD\n")
    for path in sorted(before | after):
        if path not in before:
            print(f"added    {path} — copy into {relative(WEB / path)}")
            continue
        if path not in after:
            print(f"removed  {path} — delete {relative(WEB / path)}, unless it was edited here")
            continue
        old = git("show", f"{baseline}:figma/{path}")
        new = git("show", f"HEAD:figma/{path}")
        if old == new:
            continue
        print(f"changed  {path} — merge against the baseline:")
        print(f"           git show {baseline}:figma/{path} > /tmp/web-seam-base")
        print(f"           git merge-file -p {relative(WEB / path)} /tmp/web-seam-base \\")
        print(f"               {relative(UPSTREAM / path)} > /tmp/web-seam-merged")
        print(f"           mv /tmp/web-seam-merged {relative(WEB / path)}")
    print("\na non-zero exit from `git merge-file` is the conflict count, not an error")
    return 0


def main():
    if "--plan" in sys.argv[1:]:
        return plan()

    failed = False
    for title, check in CHECKS:
        failures = check()
        if failures:
            failed = True
            print(f"FAIL  {title}")
            for failure in failures:
                print(f"        {failure}")
        else:
            print(f"ok    {title}")
    for path in sorted(UNMARKABLE):
        # Reported rather than passed over in silence: this drift is exempt, not checked.
        print(f"skip  {relative(WEB / path)}: {UNMARKABLE[path]}")
    print()
    print("the seam is intact" if not failed else "the integration has drifted")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
