<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrailBlaze.Interface\TrailBlaze.Interface.csproj" />
    <ProjectReference Include="..\TrailBlaze.Model\TrailBlaze.Model.csproj" />
  </ItemGroup>

</Project>
